apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
stringData:
  STRIPE_SECRETKEY: "sk_test_51QObtiRpZyRHFHnP5NCEqJsqcJN9FBbAKSFxwdMylIZxkZEQKMLUHH3WeIVBQp3vDMzjTuJgaXfqPiZ0gotkK9CL00OGUEXsrT"