apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexests-deployment
  labels:
    app: nexests
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nexests
  template:
    metadata:
      labels:
        app: nexests
    spec:
      containers:
        - name: nexests
          image: your-docker-repo/nexests:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/Authenticationest"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      restartPolicy: Always